### ISSUE TITLE
Upgrade alert is not shown on iOS 8 when oppenning the app and another alert is on the screen

### ISSUE THREAD

**Issue by oanaBan** [bitstadium/HockeySDK-iOS#202]
I have latest sdk version (3.8.2) and on iOS 8 when oppenning the app if there's another alert on the screen (fingerprint auth alert in my case) the Hockey upgrade alert is not shown anymore. On iOS 9 is working ok. 

Is this a known bug on your side?

**Comment by lumaxis** [comment]
Hey @oanaBan,
no, this is definitely not a known bug! Thanks for bringing it up and I'll start looking into this asap :)

**Comment by lumaxis** [comment]
Hi @oanaBan, we just released [version 3.8.3](https://github.com/bitstadium/HockeySDK-iOS/releases/tag/3.8.3) which should fix lots of alert issues. Could you check of your issue is fixed? Thanks!

**Comment by oanaBan** [comment]
Yep, the issue was fixed. Thanks a lot.

**Comment by oanaBan** [comment]
It seems that this was fixed only when opening the app from background, when opening the app after it was previously closed it's still not working.

**Comment by lumaxis** [comment]
Thanks @oanaBan for getting back to us! I'll have a look at this and try to reproduce as soon as I can.

**Comment by lumaxis** [comment]
Hey @oanaBan,
sorry for the long radio silence on this but I now finally found time to look into this.
I have tried this with a device running iOS 8.1.3 and a LocalAuthentication/TouchID alert and in my tests the HockeySDK update alert showed up with no problem.
Can you confirm that this is still an issue for this? If so, how are you setting up out SDK? Especially in relativity to the code that causes the other alert to pop up.
From what I see, we would have no way of influencing the alert's behaviour anyway since both the Touch ID alert and the UIAlertView we use are all handled by the system but if I can find a way to reproduce this, I'm happy to look into it again anyway :relaxed:
